# Email Configurations
fromEmail: mo.a.alawneh@gmail.com
password: oalhpnzxavixrdpq

# Images Parent Directory Path
path: "C:\\Users\\HITECH\\IdeaProjects\\Sakancom\\src\\main\\resources\\images/building_"